#:kivy 2.2.1
#:import pytz pytz
#:import dp kivy.metrics.dp
#:import sp kivy.metrics.sp

<ClockScreen>:
    FloatLayout:
        size: root.size
        pos: root.pos    
        Scatter:
            size_hint: 1, 1
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            do_scale: True          # Zoom erlauben
            do_translation: True    # Verschieben erlauben
            do_rotation: False      # Rotation deaktivieren
            scale_min: 0.5          # Minimaler Zoom (50% der Originalgröße)
            scale_max: 3.0          # Maximaler Zoom (300% der Originalgröße)
            Image:
                id: sky_image
                source: root.sky_image  # Dynamische Bindung an die sky_image-Eigenschaft
                size_hint: 1, 1
                pos_hint: {'center_x': 0.5, 'center_y': 0.5}
        Label:
            text: root.time         # Zeitanzeige
            font_name: app.z_font2
            font_size: sp(16)       # Anpassung mit sp
            line_height: 1.2        # Erhöht den Zeilenabstand auf 125%
            height: self.texture_size[1]  # Passt die Höhe an den Text an
            color: (0.8, 0, 0, 1)  # Farbe des Textes
            size_hint: 1, 0.9
            pos_hint: {'center_x': 0.5, 'center_y': 0.8}
        BoxLayout:
            orientation: 'vertical'
            size_hint: None, None
            height: dp(min(root.width, root.height) * 0.06)
            width: dp(min(root.width, root.height) * 0.03)  # Breite für zwei Buttons
            pos: root.width - self.width, 0  # Unten rechts
            Button:
                text: '⟳'
                font_name: 'DejaVuSans.ttf'
                font_size: sp(min(root.width, root.height) * 0.02)
                background_color: (0.8, 0.8, 0.8, 0.2) if not app.night_mode else (0.1, 0.1, 0.1, 0.4)
                size: dp(min(root.width, root.height) * 0.03), dp(min(root.width, root.height) * 0.03)
                size_hint: None, None
                on_press: app.run_totalupdate()
            Button:
                text: '⚙'
                font_name: 'DejaVuSans.ttf'
                font_size: sp(min(root.width, root.height) * 0.02)
                background_color: (0.8, 0.8, 0.8, 0.2) if not app.night_mode else (0.1, 0.1, 0.1, 0.4)
                size: dp(min(root.width, root.height) * 0.03), dp(min(root.width, root.height) * 0.03)
                size_hint: None, None
                on_press: app.switch_to_settings()